version: "3.3"

services:
  api:
    container_name: admin-cafe-api
    image: bintangrezeka/admin-cafe-api:latest
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
      - JWT_TOKEN_EXPIRED=${JWT_TOKEN_EXPIRED}
      - CONFIG_SMTP_EMAIL=${CONFIG_SMTP_EMAIL}
      - CONFIG_SMTP_PASSWORD=${CONFIG_SMTP_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public/
    depends_on:
      - mariadb-sql
    networks:
      - node_network

  proxy:
    container_name: nginx-proxy
    image: nginx
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - node_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mariadb-sql:
    container_name: mariadb-sql
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data-sql:/var/lib/mysql
    networks:
      - node_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb-sql
    networks:
      - node_network

networks:
  node_network:
