name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create .env file
      uses: skiddph/actions-env@v1
      with:
        file: .env
        prefix: 'ENV_'
      env:
        ENV_DATABASE_URL: ${{ secrets.ENV_DATABASE_URL }}
        ENV_JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
        ENV_JWT_TOKEN_EXPIRED: ${{ secrets.JWT_TOKEN_EXPIRED }}
        ENV_CONFIG_SMTP_HOST: ${{ secrets.CONFIG_SMTP_HOST }}
        ENV_CONFIG_SMTP_PORT: ${{ secrets.CONFIG_SMTP_PORT }}
        ENV_CONFIG_SMTP_EMAIL: ${{ secrets.CONFIG_SMTP_EMAIL }}
        ENV_CONFIG_SMTP_PASSWORD: ${{ secrets.CONFIG_SMTP_PASSWORD }}
        
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin-cafe-api:latest
        
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker rm -f admin-cafe-api
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/admin-cafe-api:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-cafe-api:latest
          docker run -d -p 3000:3000 --restart always -v /root/projects-api/admin-cafe-api:/usr/src/app/public --name admin-cafe-api ${{ secrets.DOCKERHUB_USERNAME }}/admin-cafe-api:latest
